include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true

linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - combinators_ordering
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - unnecessary_const
